name: Deploy Documentation to GitHub Pages

on:
    push:
        branches:
            - master # 监视主分支的推送

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build documentation
              run: pnpm run docs:build # 使用你的构建命令

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.MY_PERSONAL_TOKEN }} # 使用你的个人访问令牌
                  publish_dir: ./.vitepress/dist # 指向你的构建输出目录
                  publish_branch: main # 目标仓库的分支
                  external_repository: Zyunchao/zyunchao.github.io # 目标仓库的地址（不需要完整的 URL）
